# Generated by Django 6.0.2 on 2026-03-02
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                (
                    'image',
                    django_resized.forms.ResizedImageField(
                        force_format='WEBP',
                        quality=75,
                        size=[800, 600],
                        upload_to='trucks/',
                    ),
                ),
            ],
        ),
    ]
