# Generated by Django 6.0.2 on 2026-03-02
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                (
                    'image',
                    django_resized.forms.ResizedImageField(
                        force_format='WEBP',
                        quality=75,
                        size=[800, 600],
                        upload_to='projects/',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'key',
                    models.CharField(
                        choices=[
                            ('years', 'Years of Experience'),
                            ('projects', 'Mega Projects'),
                            ('fleet', 'Fleet Units'),
                            ('safety', 'Safety Index'),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
