# Generated by Django 6.0.2 on 2026-03-03
import uuid

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                (
                    'image',
                    django_resized.forms.ResizedImageField(
                        force_format='WEBP',
                        quality=75,
                        size=[800, 600],
                        upload_to='vehicles/',
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label_en', models.CharField(max_length=120)),
                ('label_ar', models.CharField(blank=True, max_length=120)),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('caption_ar', models.CharField(blank=True, max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_en', models.CharField(blank=True, max_length=200)),
                ('site_name_ar', models.CharField(blank=True, max_length=200)),
                ('hero_title_en', models.CharField(blank=True, max_length=200)),
                ('hero_title_ar', models.CharField(blank=True, max_length=200)),
                ('hero_desc_en', models.TextField(blank=True)),
                ('hero_desc_ar', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address_en', models.CharField(blank=True, max_length=255)),
                ('address_ar', models.CharField(blank=True, max_length=255)),
                (
                    'logo',
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        force_format='WEBP',
                        null=True,
                        quality=75,
                        size=[800, 600],
                        upload_to='settings/',
                    ),
                ),
                (
                    'hero_image',
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        force_format='WEBP',
                        null=True,
                        quality=75,
                        size=[800, 600],
                        upload_to='settings/',
                    ),
                ),
                ('refresh_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
